apiVersion: v1
kind: Service
metadata:
  name: hpe
spec:
  selector:
    app: hpe 
  ports:
  - protocol: TCP
    port: 80 
    targetPort: http 
    nodePort: 30081
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpe
  labels:
    app: hpe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpe
  template:
    metadata:
      labels:
        app: hpe
    spec:
      containers:
      - name: nginx
        image: smlinux/nginx:latest
        env:
        - name: BACKEND_HOST
          value: localhost:8080
        - name: LOG_STDOUT
          value: "true"
        ports:
        - name: http
          containerPort: 80
      - name: hpe
        image: smlinux/hello-hpe:latest
        ports:
        - containerPort: 8080
