apiVersion: v1
kind: Pod
metadata:
  name: testpod-limit-2
spec:
  containers:
  - image: smlinux/appjs
    name: test
    ports:
    - containerPort: 8080
      protocol: TCP
    resources:
      limits:
        memory: 512Mi
        cpu: 200m
      requests:
        memory: 512Mi
        cpu: 200m
